# Site settings
title: Jane Justiz
header-img: img/home-bg.png
email: janejustiz@gmail.com
copyright_name: janejustiz
description: > # this means to ignore newlines until "baseurl:"
  Jane's Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  janejustiz
learn_profile: janejustiz
email_username: janejustiz@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
